# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  Config: "Release"
  Project: "./CiCdTestLibrary"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore $Project

    - name: Build
      run: dotnet build $Project --no-restore --configuration $Config

    - name: Test
      run: dotnet test $Project --no-build --verbosity normal --configuration $Config

  staging:
    needs: build
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
    - name: "Deploy to staging for testing"
      run: dotnet test $Project --no-build --verbosity normal --configuration $Config

  release:
    needs: staging
    runs-on: ubuntu-latest
    environment: release

    steps:
    - name: "Release code"
      run: dotnet test $Project --no-build --verbosity normal --configuration $Config

